# Generated by Django 2.2.7 on 2019-11-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='create_by',
        ),
    ]
