# Generated by Django 2.2.7 on 2019-11-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0006_auto_20191122_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
