# Generated by Django 2.2.7 on 2019-11-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0007_book_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
