# Generated by Django 2.2.7 on 2019-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0008_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
