# Generated by Django 2.2.7 on 2019-11-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0009_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_url',
        ),
    ]
