# Generated by Django 2.2.7 on 2019-11-28 22:15

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0010_auto_20191123_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=computed_property.fields.ComputedCharField(compute_from='calculate_status', default='uncompleted', editable=False, max_length=30),
        ),
    ]
