# Generated by Django 2.2.7 on 2019-11-28 22:22

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0011_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=computed_property.fields.ComputedCharField(compute_from='calculate_status', editable=False, max_length=30, null=True),
        ),
    ]
