# Generated by Django 2.2.7 on 2019-11-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segnalibre_app', '0012_auto_20191128_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
